### ISSUE TITLE
Does this work for unpaired images? Or only for paired images like pix2pix?

### ISSUE THREAD

**Issue by ankur-chr** [laxmaniron/MSG-U-Net#2]
Hi @laxmaniron,

I am looking at translating day images to night time, and would like to understand if this model relies on paired images only? Or can it handle unpaired images as well?

**Comment by laxmaniron** [comment]
Hi cankur, For now, it is only applicable for paired image to image translation, but you can experiment in unpaired image to image translation by changing loss functions, training structure etc. If you need like an overview or guidance, you can email me at laxy0016@gmail.com

**Comment by ankur-chr** [comment]
Thanks @laxmaniron !
